insert into public.products (slug, name, code, description, specs, applications, industries, display_order) values
('industrial-fuel-oil', 'Industrial Fuel Oil', 'IFO-380',
 'High-grade thermal energy source for boilers, furnaces, and power generation. Consistent calorific value for uninterrupted operations.',
 '[{"label":"Viscosity","value":"380 cSt @ 50°C"},{"label":"Flash Point","value":">66°C"},{"label":"Sulfur","value":"<3.5%"}]',
 array['Boilers','Furnaces','Power generation'], array['Power & Energy','Manufacturing'], 1),
('base-oil-sn500', 'Base Oil SN500', 'SN-500',
 'Premium lubricant base stock for engine oils, hydraulic fluids, and industrial lubricant formulations.',
 '[{"label":"Density","value":"0.865 g/ml"},{"label":"Viscosity Index","value":">95"},{"label":"Pour Point","value":"-6°C"}]',
 array['Engine oils','Hydraulic fluids','Industrial lubricants'], array['Automotive','Lubricants'], 2),
('paving-bitumen-vg30', 'Paving Bitumen', 'VG-30',
 'Durable paving-grade bitumen for highways, bridges, and urban road construction projects. BIS IS 73:2013 compliant.',
 '[{"label":"Penetration","value":"60/70"},{"label":"Softening Pt","value":">47°C"},{"label":"Ductility","value":">75 cm"}]',
 array['Highways','Bridges','Urban roads'], array['Road Construction','Infrastructure'], 3),
('rubber-process-oil', 'Rubber Process Oil', 'RPO-A',
 'Aromatic and naphthenic process oils for rubber compounding, tire manufacturing, and polymer processing.',
 '[{"label":"Aniline Point","value":"90°C"},{"label":"Viscosity","value":"95 cSt @ 40°C"},{"label":"Flash Point","value":">220°C"}]',
 array['Rubber compounding','Tire manufacturing','Polymer processing'], array['Rubber','Polymers'], 4),
('light-diesel-oil', 'Light Diesel Oil', 'LDO-IN',
 'Clean-burning, efficient combustion fuel for DG sets, industrial burners, and start-up fuel applications.',
 '[{"label":"Flash Point","value":">66°C"},{"label":"Density","value":"0.85-0.87"},{"label":"Cetane No.","value":">45"}]',
 array['DG sets','Industrial burners','Start-up fuel'], array['Power','Manufacturing'], 5),
('mineral-turpentine-oil', 'Mineral Turpentine Oil', 'MTO',
 'Versatile industrial solvent for paint thinning, surface preparation, degreasing, and chemical extraction.',
 '[{"label":"Aromatics","value":"14%"},{"label":"Distillation","value":"130-200°C"},{"label":"Purity","value":">99%"}]',
 array['Paint thinning','Surface preparation','Degreasing'], array['Paint & Coatings','Chemical'], 6),
('base-oil-sn150', 'Base Oil SN150', 'SN-150',
 'Lighter-viscosity lubricant base stock for low-temperature hydraulic fluids and light industrial lubricant blends.',
 '[{"label":"Density","value":"0.855 g/ml"},{"label":"Viscosity Index","value":">90"},{"label":"Pour Point","value":"-9°C"}]',
 array['Hydraulic fluids','Light industrial lubricants'], array['Automotive','Lubricants'], 7),
('petroleum-jelly', 'Petroleum Jelly', 'PJ-WHITE',
 'Ultra-refined, pharmacopoeia-grade petroleum jelly for pharmaceutical, cosmetic, and personal-care formulations.',
 '[{"label":"Melting Point","value":"38-60°C"},{"label":"Color","value":"White, USP grade"},{"label":"Purity","value":"Pharma grade"}]',
 array['Pharmaceutical formulations','Cosmetics','Personal care'], array['Pharmaceutical'], 8)
;
